namespace EyeReminder;

/// <summary>Chrome text for the CJK, Hindi and Arabic packs. See <see cref="Ui"/>.</summary>
internal static partial class Ui
{
    private static void RegisterAsian()
    {
        Packs["ja"] = new(StringComparer.OrdinalIgnoreCase)
        {
            ["tray.tooltip"] = "EyeReminder — 20/20/20ルール",
            ["tray.next"] = "次の休憩まで {0}",
            ["tray.pausedUntil"] = "{0} まで一時停止",
            ["tray.idle"] = "操作がないため一時停止中",
            ["tray.test"] = "今すぐテスト",
            ["tray.reset"] = "タイマーをリセット",
            ["tray.pause"] = "1時間 一時停止",
            ["tray.resume"] = "再開",
            ["tray.settings"] = "設定...",
            ["tray.exit"] = "終了",

            ["win.title"] = "EyeReminder — 設定",
            ["sec.reminder"] = "リマインダー",
            ["sec.idle"] = "無操作",
            ["sec.language"] = "言語",
            ["sec.style"] = "スタイル",
            ["sec.position"] = "画面上の位置",
            ["sec.texts"] = "テキスト",
            ["sec.sound"] = "サウンド",
            ["sec.system"] = "システム",

            ["lbl.frequency"] = "間隔",
            ["lbl.break"] = "休憩の長さ",
            ["lbl.countdown"] = "カウントダウン",
            ["lbl.pauseAfter"] = "一時停止するまで",
            ["lbl.accent"] = "アクセントカラー",
            ["lbl.size"] = "サイズ",
            ["lbl.opacity"] = "不透明度",
            ["lbl.volume"] = "音量",
            ["lbl.textTitle"] = "タイトル",
            ["lbl.textCountdown"] = "カウントダウン中",
            ["lbl.textBreak"] = "休憩中",

            ["chk.idle"] = "PCを使っていないときは一時停止",
            ["chk.startupNotice"] = "起動時にバックグラウンド実行を知らせる",
            ["chk.allScreens"] = "すべてのモニターに表示",
            ["chk.soundStart"] = "開始時に音を鳴らす",
            ["chk.soundEnd"] = "終了時にも鳴らす",
            ["chk.customText"] = "自分でテキストを書く",
            ["chk.startup"] = "Windowsと一緒に起動",

            ["btn.browse"] = "参照",
            ["btn.test"] = "テスト",
            ["btn.preview"] = "プレビュー",
            ["btn.cancel"] = "キャンセル",
            ["btn.save"] = "保存",

            ["hint.countdown"] = "休憩前に3, 2, 1。0 で予告なし。",
            ["hint.idle"] = "戻ると間隔は最初から数え直します。",
            ["hint.customText"] = "オフなら言語のテキストを使います。{0} = 秒数。",
            ["hint.sound"] = "空欄 = 内蔵サウンド。どの .wav でも使えます。",
            ["hint.startup"] = "登録されます: {0}",

            ["unit.min"] = "分",
            ["unit.sec"] = "秒",
            ["opt.noCountdown"] = "なし",

            ["theme.dark"] = "ダーク",
            ["theme.light"] = "ライト",
            ["theme.warm"] = "ウォーム",
            ["theme.minimal"] = "ミニマル",

            ["pos.topLeft"] = "左上",
            ["pos.topCenter"] = "上中央",
            ["pos.topRight"] = "右上",
            ["pos.bottomLeft"] = "左下",
            ["pos.center"] = "中央",
            ["pos.bottomRight"] = "右下",

            ["accent.theme"] = "テーマの色",
            ["accent.teal"] = "ティール",
            ["accent.blue"] = "ブルー",
            ["accent.amber"] = "アンバー",
            ["accent.rose"] = "ローズ",
            ["accent.green"] = "グリーン",
            ["accent.violet"] = "バイオレット",

            ["lang.auto"] = "自動",
            ["dlg.saveFailed"] = "{0} に書き込めませんでした。\n変更は今は有効ですが、再起動すると失われます。",
            ["dlg.registryFailed"] = "スタートアップの登録に失敗しました。他の設定は保存されました。",
            ["file.pickSound"] = "サウンドを選択",
            ["file.wavFilter"] = "WAV オーディオ (*.wav)|*.wav"
        };

        Packs["ko"] = new(StringComparer.OrdinalIgnoreCase)
        {
            ["tray.tooltip"] = "EyeReminder — 20/20/20 규칙",
            ["tray.next"] = "다음 휴식까지 {0}",
            ["tray.pausedUntil"] = "{0}까지 일시 중지",
            ["tray.idle"] = "사용하지 않아 일시 중지됨",
            ["tray.test"] = "지금 테스트",
            ["tray.reset"] = "타이머 초기화",
            ["tray.pause"] = "1시간 일시 중지",
            ["tray.resume"] = "다시 시작",
            ["tray.settings"] = "설정...",
            ["tray.exit"] = "종료",

            ["win.title"] = "EyeReminder — 설정",
            ["sec.reminder"] = "알림",
            ["sec.idle"] = "미사용",
            ["sec.language"] = "언어",
            ["sec.style"] = "스타일",
            ["sec.position"] = "화면 위치",
            ["sec.texts"] = "텍스트",
            ["sec.sound"] = "소리",
            ["sec.system"] = "시스템",

            ["lbl.frequency"] = "주기",
            ["lbl.break"] = "휴식 길이",
            ["lbl.countdown"] = "카운트다운",
            ["lbl.pauseAfter"] = "일시 중지 기준",
            ["lbl.accent"] = "강조 색상",
            ["lbl.size"] = "크기",
            ["lbl.opacity"] = "불투명도",
            ["lbl.volume"] = "음량",
            ["lbl.textTitle"] = "제목",
            ["lbl.textCountdown"] = "카운트다운 중",
            ["lbl.textBreak"] = "휴식 중",

            ["chk.idle"] = "PC를 사용하지 않으면 일시 중지",
            ["chk.startupNotice"] = "시작할 때 백그라운드 실행을 알림",
            ["chk.allScreens"] = "모든 모니터에 표시",
            ["chk.soundStart"] = "시작할 때 소리 재생",
            ["chk.soundEnd"] = "끝날 때도 재생",
            ["chk.customText"] = "내 텍스트 사용",
            ["chk.startup"] = "Windows 시작 시 실행",

            ["btn.browse"] = "찾아보기",
            ["btn.test"] = "테스트",
            ["btn.preview"] = "미리 보기",
            ["btn.cancel"] = "취소",
            ["btn.save"] = "저장",

            ["hint.countdown"] = "휴식 전 3, 2, 1. 0이면 예고 없음.",
            ["hint.idle"] = "돌아오면 주기가 처음부터 다시 시작됩니다.",
            ["hint.customText"] = "해제하면 언어 텍스트를 사용합니다. {0} = 초.",
            ["hint.sound"] = "비우면 기본 소리. 모든 .wav 사용 가능.",
            ["hint.startup"] = "등록됩니다: {0}",

            ["unit.min"] = "분",
            ["unit.sec"] = "초",
            ["opt.noCountdown"] = "없음",

            ["theme.dark"] = "다크",
            ["theme.light"] = "라이트",
            ["theme.warm"] = "웜",
            ["theme.minimal"] = "미니멀",

            ["pos.topLeft"] = "왼쪽 위",
            ["pos.topCenter"] = "가운데 위",
            ["pos.topRight"] = "오른쪽 위",
            ["pos.bottomLeft"] = "왼쪽 아래",
            ["pos.center"] = "가운데",
            ["pos.bottomRight"] = "오른쪽 아래",

            ["accent.theme"] = "테마 색상",
            ["accent.teal"] = "청록",
            ["accent.blue"] = "파랑",
            ["accent.amber"] = "호박",
            ["accent.rose"] = "장미",
            ["accent.green"] = "초록",
            ["accent.violet"] = "보라",

            ["lang.auto"] = "자동",
            ["dlg.saveFailed"] = "{0}에 쓸 수 없습니다.\n변경 사항은 지금 적용되지만 다시 시작하면 사라집니다.",
            ["dlg.registryFailed"] = "시작 프로그램 키를 쓸 수 없습니다. 나머지는 저장되었습니다.",
            ["file.pickSound"] = "소리 선택",
            ["file.wavFilter"] = "WAV 오디오 (*.wav)|*.wav"
        };

        Packs["zh-Hans"] = new(StringComparer.OrdinalIgnoreCase)
        {
            ["tray.tooltip"] = "EyeReminder — 20/20/20 法则",
            ["tray.next"] = "距离下次休息 {0}",
            ["tray.pausedUntil"] = "暂停至 {0}",
            ["tray.idle"] = "因闲置而暂停",
            ["tray.test"] = "立即测试",
            ["tray.reset"] = "重置计时",
            ["tray.pause"] = "暂停 1 小时",
            ["tray.resume"] = "继续",
            ["tray.settings"] = "设置...",
            ["tray.exit"] = "退出",

            ["win.title"] = "EyeReminder — 设置",
            ["sec.reminder"] = "提醒",
            ["sec.idle"] = "闲置",
            ["sec.language"] = "语言",
            ["sec.style"] = "样式",
            ["sec.position"] = "屏幕位置",
            ["sec.texts"] = "文本",
            ["sec.sound"] = "声音",
            ["sec.system"] = "系统",

            ["lbl.frequency"] = "频率",
            ["lbl.break"] = "休息时长",
            ["lbl.countdown"] = "倒计时",
            ["lbl.pauseAfter"] = "闲置多久后暂停",
            ["lbl.accent"] = "强调色",
            ["lbl.size"] = "大小",
            ["lbl.opacity"] = "不透明度",
            ["lbl.volume"] = "音量",
            ["lbl.textTitle"] = "标题",
            ["lbl.textCountdown"] = "倒计时期间",
            ["lbl.textBreak"] = "休息期间",

            ["chk.idle"] = "不使用电脑时暂停",
            ["chk.startupNotice"] = "启动时提示正在后台运行",
            ["chk.allScreens"] = "在所有显示器上显示",
            ["chk.soundStart"] = "开始时播放声音",
            ["chk.soundEnd"] = "结束时也播放",
            ["chk.customText"] = "使用自定义文本",
            ["chk.startup"] = "开机时启动",

            ["btn.browse"] = "浏览",
            ["btn.test"] = "测试",
            ["btn.preview"] = "预览",
            ["btn.cancel"] = "取消",
            ["btn.save"] = "保存",

            ["hint.countdown"] = "休息前 3、2、1。设为 0 则直接开始。",
            ["hint.idle"] = "回来后间隔会从头开始计算。",
            ["hint.customText"] = "不勾选则使用所选语言的文本。{0} = 秒数。",
            ["hint.sound"] = "留空 = 内置声音。支持任何 .wav。",
            ["hint.startup"] = "将注册：{0}",

            ["unit.min"] = "分钟",
            ["unit.sec"] = "秒",
            ["opt.noCountdown"] = "无",

            ["theme.dark"] = "深色",
            ["theme.light"] = "浅色",
            ["theme.warm"] = "暖色",
            ["theme.minimal"] = "极简",

            ["pos.topLeft"] = "左上",
            ["pos.topCenter"] = "顶部居中",
            ["pos.topRight"] = "右上",
            ["pos.bottomLeft"] = "左下",
            ["pos.center"] = "居中",
            ["pos.bottomRight"] = "右下",

            ["accent.theme"] = "跟随主题",
            ["accent.teal"] = "青色",
            ["accent.blue"] = "蓝色",
            ["accent.amber"] = "琥珀色",
            ["accent.rose"] = "玫瑰色",
            ["accent.green"] = "绿色",
            ["accent.violet"] = "紫色",

            ["lang.auto"] = "自动",
            ["dlg.saveFailed"] = "无法写入 {0}。\n更改现在生效，但重启后会丢失。",
            ["dlg.registryFailed"] = "无法写入开机启动项。其余设置已保存。",
            ["file.pickSound"] = "选择声音",
            ["file.wavFilter"] = "WAV 音频 (*.wav)|*.wav"
        };

        Packs["zh-Hant"] = new(StringComparer.OrdinalIgnoreCase)
        {
            ["tray.tooltip"] = "EyeReminder — 20/20/20 法則",
            ["tray.next"] = "距離下次休息 {0}",
            ["tray.pausedUntil"] = "暫停至 {0}",
            ["tray.idle"] = "因閒置而暫停",
            ["tray.test"] = "立即測試",
            ["tray.reset"] = "重設計時",
            ["tray.pause"] = "暫停 1 小時",
            ["tray.resume"] = "繼續",
            ["tray.settings"] = "設定...",
            ["tray.exit"] = "結束",

            ["win.title"] = "EyeReminder — 設定",
            ["sec.reminder"] = "提醒",
            ["sec.idle"] = "閒置",
            ["sec.language"] = "語言",
            ["sec.style"] = "樣式",
            ["sec.position"] = "螢幕位置",
            ["sec.texts"] = "文字",
            ["sec.sound"] = "音效",
            ["sec.system"] = "系統",

            ["lbl.frequency"] = "頻率",
            ["lbl.break"] = "休息長度",
            ["lbl.countdown"] = "倒數計時",
            ["lbl.pauseAfter"] = "閒置多久後暫停",
            ["lbl.accent"] = "強調色",
            ["lbl.size"] = "大小",
            ["lbl.opacity"] = "不透明度",
            ["lbl.volume"] = "音量",
            ["lbl.textTitle"] = "標題",
            ["lbl.textCountdown"] = "倒數期間",
            ["lbl.textBreak"] = "休息期間",

            ["chk.idle"] = "沒有使用電腦時暫停",
            ["chk.startupNotice"] = "啟動時提示正在背景執行",
            ["chk.allScreens"] = "在所有螢幕上顯示",
            ["chk.soundStart"] = "開始時播放音效",
            ["chk.soundEnd"] = "結束時也播放",
            ["chk.customText"] = "使用自訂文字",
            ["chk.startup"] = "開機時啟動",

            ["btn.browse"] = "瀏覽",
            ["btn.test"] = "測試",
            ["btn.preview"] = "預覽",
            ["btn.cancel"] = "取消",
            ["btn.save"] = "儲存",

            ["hint.countdown"] = "休息前 3、2、1。設為 0 則直接開始。",
            ["hint.idle"] = "回來後間隔會從頭開始計算。",
            ["hint.customText"] = "未勾選則使用所選語言的文字。{0} = 秒數。",
            ["hint.sound"] = "留空 = 內建音效。支援任何 .wav。",
            ["hint.startup"] = "將註冊：{0}",

            ["unit.min"] = "分鐘",
            ["unit.sec"] = "秒",
            ["opt.noCountdown"] = "無",

            ["theme.dark"] = "深色",
            ["theme.light"] = "淺色",
            ["theme.warm"] = "暖色",
            ["theme.minimal"] = "極簡",

            ["pos.topLeft"] = "左上",
            ["pos.topCenter"] = "頂端置中",
            ["pos.topRight"] = "右上",
            ["pos.bottomLeft"] = "左下",
            ["pos.center"] = "置中",
            ["pos.bottomRight"] = "右下",

            ["accent.theme"] = "跟隨主題",
            ["accent.teal"] = "青色",
            ["accent.blue"] = "藍色",
            ["accent.amber"] = "琥珀色",
            ["accent.rose"] = "玫瑰色",
            ["accent.green"] = "綠色",
            ["accent.violet"] = "紫色",

            ["lang.auto"] = "自動",
            ["dlg.saveFailed"] = "無法寫入 {0}。\n變更現在生效，但重新啟動後會消失。",
            ["dlg.registryFailed"] = "無法寫入開機啟動項。其餘設定已儲存。",
            ["file.pickSound"] = "選擇音效",
            ["file.wavFilter"] = "WAV 音訊 (*.wav)|*.wav"
        };

        Packs["hi"] = new(StringComparer.OrdinalIgnoreCase)
        {
            ["tray.tooltip"] = "EyeReminder — 20/20/20 नियम",
            ["tray.next"] = "अगला ब्रेक {0} में",
            ["tray.pausedUntil"] = "{0} तक रोका गया",
            ["tray.idle"] = "निष्क्रियता के कारण रोका गया",
            ["tray.test"] = "अभी जांचें",
            ["tray.reset"] = "टाइमर रीसेट करें",
            ["tray.pause"] = "1 घंटे के लिए रोकें",
            ["tray.resume"] = "फिर से शुरू करें",
            ["tray.settings"] = "सेटिंग्स...",
            ["tray.exit"] = "बंद करें",

            ["win.title"] = "EyeReminder — सेटिंग्स",
            ["sec.reminder"] = "रिमाइंडर",
            ["sec.idle"] = "निष्क्रियता",
            ["sec.language"] = "भाषा",
            ["sec.style"] = "शैली",
            ["sec.position"] = "स्क्रीन पर स्थान",
            ["sec.texts"] = "टेक्स्ट",
            ["sec.sound"] = "ध्वनि",
            ["sec.system"] = "सिस्टम",

            ["lbl.frequency"] = "अंतराल",
            ["lbl.break"] = "ब्रेक की अवधि",
            ["lbl.countdown"] = "काउंटडाउन",
            ["lbl.pauseAfter"] = "इतने समय बाद रोकें",
            ["lbl.accent"] = "एक्सेंट रंग",
            ["lbl.size"] = "आकार",
            ["lbl.opacity"] = "अपारदर्शिता",
            ["lbl.volume"] = "वॉल्यूम",
            ["lbl.textTitle"] = "शीर्षक",
            ["lbl.textCountdown"] = "काउंटडाउन के दौरान",
            ["lbl.textBreak"] = "ब्रेक के दौरान",

            ["chk.idle"] = "जब मैं पीसी इस्तेमाल न करूं तब रोकें",
            ["chk.startupNotice"] = "शुरू होने पर बताएं कि यह पृष्ठभूमि में चल रहा है",
            ["chk.allScreens"] = "सभी मॉनिटर पर दिखाएं",
            ["chk.soundStart"] = "शुरू में ध्वनि बजाएं",
            ["chk.soundEnd"] = "अंत में भी बजाएं",
            ["chk.customText"] = "अपना टेक्स्ट लिखें",
            ["chk.startup"] = "Windows के साथ शुरू करें",

            ["btn.browse"] = "ब्राउज़ करें",
            ["btn.test"] = "जांचें",
            ["btn.preview"] = "पूर्वावलोकन",
            ["btn.cancel"] = "रद्द करें",
            ["btn.save"] = "सहेजें",

            ["hint.countdown"] = "ब्रेक से पहले 3, 2, 1। 0 = कोई चेतावनी नहीं।",
            ["hint.idle"] = "लौटने पर अंतराल शुरू से गिना जाएगा।",
            ["hint.customText"] = "अनचेक होने पर भाषा का टेक्स्ट चलेगा। {0} = सेकंड।",
            ["hint.sound"] = "खाली = अंतर्निहित ध्वनि। कोई भी .wav चलेगा।",
            ["hint.startup"] = "दर्ज किया जाएगा: {0}",

            ["unit.min"] = "मिनट",
            ["unit.sec"] = "से",
            ["opt.noCountdown"] = "कोई नहीं",

            ["theme.dark"] = "गहरा",
            ["theme.light"] = "हल्का",
            ["theme.warm"] = "गर्म",
            ["theme.minimal"] = "न्यूनतम",

            ["pos.topLeft"] = "ऊपर बाएं",
            ["pos.topCenter"] = "ऊपर बीच में",
            ["pos.topRight"] = "ऊपर दाएं",
            ["pos.bottomLeft"] = "नीचे बाएं",
            ["pos.center"] = "बीच में",
            ["pos.bottomRight"] = "नीचे दाएं",

            ["accent.theme"] = "थीम से",
            ["accent.teal"] = "टील",
            ["accent.blue"] = "नीला",
            ["accent.amber"] = "एम्बर",
            ["accent.rose"] = "गुलाबी",
            ["accent.green"] = "हरा",
            ["accent.violet"] = "बैंगनी",

            ["lang.auto"] = "स्वचालित",
            ["dlg.saveFailed"] = "{0} में नहीं लिख सके।\nबदलाव अभी लागू हैं पर पुनः शुरू करने पर चले जाएंगे।",
            ["dlg.registryFailed"] = "स्टार्टअप कुंजी नहीं लिख सके। बाकी सब सहेज लिया गया।",
            ["file.pickSound"] = "ध्वनि चुनें",
            ["file.wavFilter"] = "WAV ऑडियो (*.wav)|*.wav"
        };

        Packs["ar"] = new(StringComparer.OrdinalIgnoreCase)
        {
            ["tray.tooltip"] = "EyeReminder — قاعدة 20/20/20",
            ["tray.next"] = "الاستراحة التالية بعد {0}",
            ["tray.pausedUntil"] = "متوقف حتى {0}",
            ["tray.idle"] = "متوقف بسبب عدم النشاط",
            ["tray.test"] = "جرّب الآن",
            ["tray.reset"] = "إعادة ضبط المؤقت",
            ["tray.pause"] = "إيقاف لمدة ساعة",
            ["tray.resume"] = "استئناف",
            ["tray.settings"] = "الإعدادات...",
            ["tray.exit"] = "خروج",

            ["win.title"] = "EyeReminder — الإعدادات",
            ["sec.reminder"] = "التذكير",
            ["sec.idle"] = "عدم النشاط",
            ["sec.language"] = "اللغة",
            ["sec.style"] = "النمط",
            ["sec.position"] = "الموضع على الشاشة",
            ["sec.texts"] = "النصوص",
            ["sec.sound"] = "الصوت",
            ["sec.system"] = "النظام",

            ["lbl.frequency"] = "التكرار",
            ["lbl.break"] = "مدة الاستراحة",
            ["lbl.countdown"] = "العد التنازلي",
            ["lbl.pauseAfter"] = "الإيقاف بعد",
            ["lbl.accent"] = "لون التمييز",
            ["lbl.size"] = "الحجم",
            ["lbl.opacity"] = "العتامة",
            ["lbl.volume"] = "مستوى الصوت",
            ["lbl.textTitle"] = "العنوان",
            ["lbl.textCountdown"] = "أثناء العد التنازلي",
            ["lbl.textBreak"] = "أثناء الاستراحة",

            ["chk.idle"] = "الإيقاف عندما لا أستخدم الجهاز",
            ["chk.startupNotice"] = "التنبيه عند البدء أنه يعمل في الخلفية",
            ["chk.allScreens"] = "العرض على كل الشاشات",
            ["chk.soundStart"] = "تشغيل صوت في البداية",
            ["chk.soundEnd"] = "تشغيله في النهاية أيضًا",
            ["chk.customText"] = "كتابة نصوصي الخاصة",
            ["chk.startup"] = "البدء مع Windows",

            ["btn.browse"] = "استعراض",
            ["btn.test"] = "تجربة",
            ["btn.preview"] = "معاينة",
            ["btn.cancel"] = "إلغاء",
            ["btn.save"] = "حفظ",

            ["hint.countdown"] = "‏3، 2، 1 قبل الاستراحة. 0 = بدون تنبيه.",
            ["hint.idle"] = "عند العودة تبدأ الفترة من جديد.",
            ["hint.customText"] = "بدون تحديد تُستخدم نصوص اللغة. ‏{0} = عدد الثواني.",
            ["hint.sound"] = "فارغ = الصوت المدمج. يقبل أي ملف ‎.wav‎.",
            ["hint.startup"] = "سيتم التسجيل: {0}",

            ["unit.min"] = "د",
            ["unit.sec"] = "ث",
            ["opt.noCountdown"] = "بدون",

            ["theme.dark"] = "داكن",
            ["theme.light"] = "فاتح",
            ["theme.warm"] = "دافئ",
            ["theme.minimal"] = "بسيط",

            ["pos.topLeft"] = "أعلى اليسار",
            ["pos.topCenter"] = "أعلى الوسط",
            ["pos.topRight"] = "أعلى اليمين",
            ["pos.bottomLeft"] = "أسفل اليسار",
            ["pos.center"] = "الوسط",
            ["pos.bottomRight"] = "أسفل اليمين",

            ["accent.theme"] = "من النمط",
            ["accent.teal"] = "فيروزي",
            ["accent.blue"] = "أزرق",
            ["accent.amber"] = "كهرماني",
            ["accent.rose"] = "وردي",
            ["accent.green"] = "أخضر",
            ["accent.violet"] = "بنفسجي",

            ["lang.auto"] = "تلقائي",
            ["dlg.saveFailed"] = "تعذّرت الكتابة إلى {0}.\nالتغييرات سارية الآن لكنها ستضيع عند إعادة التشغيل.",
            ["dlg.registryFailed"] = "تعذّرت كتابة مفتاح بدء التشغيل. تم حفظ الباقي.",
            ["file.pickSound"] = "اختيار صوت",
            ["file.wavFilter"] = "صوت WAV (*.wav)|*.wav"
        };
    }
}
